### Negative: Admin creates user with password of 7 characters
POST {{baseUrl}}/api/v1/admin/users
Content-Type: application/json
Accept: */*
Authorization: {{authToken}}

{
  "username": "{{randomUsername}}",
  "password": "{{shortPassword}}",
  "role": "USER"
}

