### Negative: Admin creates user with invalid role. Allowed: ADMIN, USER
POST {{baseUrl}}/api/v1/admin/users
Content-Type: application/json
Accept: */*
Authorization: {{authToken}}

{
  "username": "{{randomUsername}}",
  "password": "{{randomPassword}}",
  "role": "Negative"
}

