### Negative: Transfer negative amount
POST {{baseUrl}}/api/v1/accounts/transfer
Content-Type: application/json
Accept: */*
Authorization: {{authToken2}}

{
  "senderAccountId": 1,
  "receiverAccountId": 52,
  "amount": -100
}

