### Positive: User can deposit to account max amount 5000 Copy
POST {{baseUrl}}/api/v1/accounts/deposit
Content-Type: application/json
Accept: */*
Authorization: {{authToken2}}

{
  "id": 1,
  "balance": 5000
}

